### ISSUE TITLE
illegalFormatConversionException

### ISSUE THREAD

**Issue by CSM413** [bubuntux/poker-engine#5]
Will you please help me with this?
i am making application research but this happen everytime i try and play it. 

Exception in thread "main" java.util.IllegalFormatConversionException: d != java.math.BigDecimal
	at java.base/java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4515)
	at java.base/java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:3066)
	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3021)
	at java.base/java.util.Formatter.format(Formatter.java:2791)
	at java.base/java.util.Formatter.format(Formatter.java:2728)
	at java.base/java.lang.String.format(String.java:4386)
	at org.dsaw.poker.engine.Table.doShowdown(Table.java:675)
	at org.dsaw.poker.engine.Table.playHand(Table.java:214)
	at org.dsaw.poker.engine.Table.run(Table.java:154)
	at org.dsaw.poker.engine.gui.Main.<init>(Main.java:143)
	at org.dsaw.poker.engine.gui.Main.main(Main.java:153)
	
	edit: could you also tell me what data structure this uses as well as it's algorithm?
	would be greatly appreciated if you could.

**Comment by bubuntux** [comment]
Repo archived; closing as stale
